### PR TITLE
Synchronize Gemini to the latest arkworks-rs algebra 0.4.0

### PR DESCRIPTION
**Pull request by weikengchen**
This PR updates the Gemini regarding DenseUVPolynomial, VariableBaseMSM, Group, to_bytes.

### CODE REVIEW

**Comment by mmaker** [comment]
Thanks! this has been already fixed on our end in https://github.com/mmaker/ark-gemini/tree/feature/transparent  and will be synched into main soon.

**Comment by weikengchen** [comment]
(can you also make it work with "stable" instead of "nightly"?)

**Comment by weikengchen** [comment]
I think you may want to reopen this PR as the delta is growing.

**Comment by mmaker** [comment]
there are two monsters here: 
1- making gemini compatible with rust stable
2- align gemini with algebra
which monster are we trying to fight?
To make sure I'm not breaking anything, perhaps you can make two different pull requests? Can you make the commitment messages a bit more descriptive?

**Comment by weikengchen** [comment]
Actually this PR is not seeking to make it stable---I still don't know how to do that

**Pull request closed without merging**
